name: Build and deploy Jekyll site to Azure

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1'
      
      - name: Install Jekyll
        run: gem install bundler jekyll
      
      - name: Build Jekyll site
        run: jekyll build
      
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: site
          path: _site/
  
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: site
      
      - name: Deploy to Azure
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'hmis-ramirezsoto-blog'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_7A532641598F45D1A5665C3CB22409AC }}
          package: .
